import { Brand, Product } from '@/types'

export const brands: Brand[] = [
  { id: '1', name: 'Amalfy', state: 'SP', category: 'Roupas', slug: 'amalfy' },
  { id: '2', name: 'Saynalô', state: 'RJ', category: 'Roupas', slug: 'saynalo' },
  { id: '3', name: 'Elis Cardim', state: 'BA', category: 'Roupas', slug: 'elis-cardim' },
  { id: '4', name: 'Morada', state: 'PB', category: 'Acessórios', slug: 'morada' },
  { id: '5', name: 'Dendezeiro', state: 'BA', category: 'Roupas', slug: 'dendezeiro' },
  { id: '6', name: 'Santa Maria', state: 'RJ', category: 'Acessórios', slug: 'santa-maria' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Vestido Linho Estruturado',
    brand: 'Amalfy',
    brandSlug: 'amalfy',
    price: 489,
    category: 'Roupas',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'vestido-linho-estruturado',
  },
  {
    id: '2',
    name: 'Blusa Transpassada',
    brand: 'Amalfy',
    brandSlug: 'amalfy',
    price: 279,
    category: 'Roupas',
    sizes: ['PP', 'P', 'M', 'G'],
    slug: 'blusa-transpassada',
  },
  {
    id: '3',
    name: 'Conjunto Cropped Saia',
    brand: 'Saynalô',
    brandSlug: 'saynalo',
    price: 560,
    category: 'Roupas',
    sizes: ['P', 'M', 'G', 'GG'],
    slug: 'conjunto-cropped-saia',
  },
  {
    id: '4',
    name: 'Calça Pantalona Alfaiataria',
    brand: 'Elis Cardim',
    brandSlug: 'elis-cardim',
    price: 398,
    category: 'Roupas',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'calca-pantalona-alfaiataria',
  },
  {
    id: '5',
    name: 'Colar Cerâmica Artesanal',
    brand: 'Morada',
    brandSlug: 'morada',
    price: 189,
    category: 'Acessórios',
    sizes: ['M'],
    slug: 'colar-ceramica-artesanal',
  },
  {
    id: '6',
    name: 'Vestido Bordado Dendê',
    brand: 'Dendezeiro',
    brandSlug: 'dendezeiro',
    price: 620,
    category: 'Roupas',
    sizes: ['P', 'M', 'G', 'GG'],
    slug: 'vestido-bordado-dende',
  },
  {
    id: '7',
    name: 'Brinco Concha Dourado',
    brand: 'Santa Maria',
    brandSlug: 'santa-maria',
    price: 145,
    category: 'Acessórios',
    sizes: ['M'],
    slug: 'brinco-concha-dourado',
  },
  {
    id: '8',
    name: 'Camisa Linho Oversized',
    brand: 'Saynalô',
    brandSlug: 'saynalo',
    price: 340,
    category: 'Roupas',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'camisa-linho-oversized',
  },
]

export const categories = ['Novidades', 'Roupas', 'Acessórios', 'Marcas', 'Sale']
