import { Brand, Product } from '@/types'

export const brands: Brand[] = [
  {
    id: '1',
    name: 'Amalfi',
    state: 'SP',
    category: 'Beachwear',
    slug: 'amalfi',
    description: 'Amalfi Swim & Resortwear é uma marca paulistana especializada em moda praia e resort de alto padrão. Com tecidos sofisticados e design atemporal, cada peça é pensada para a mulher que vive o verão com elegância — da piscina ao jantar à beira-mar.',
    logo: '/logo-amalfi.png',
  },
  {
    id: '2',
    name: 'Ares',
    state: 'SP',
    category: 'Roupas',
    slug: 'ares',
    description: 'Ares é uma marca brasileira contemporânea focada em blusas, calças e peças do dia a dia com acabamento refinado. Com nomes de cidades ao redor do mundo em suas coleções, a marca une cosmopolitismo e praticidade no guarda-roupa feminino.',
  },
  {
    id: '3',
    name: 'Dress To',
    state: 'RJ',
    category: 'Roupas',
    slug: 'dress-to',
    description: 'Nascida em Niterói, Dress To é referência em moda feminina contemporânea com preços acessíveis. Vestidos, blusas, macacões e calças com design moderno e muita personalidade — para quem quer se vestir bem sem abrir mão do estilo.',
    logo: '/logo-dress-to.png',
  },
  {
    id: '4',
    name: 'Panô',
    state: 'RJ',
    category: 'Resortwear',
    slug: 'pano',
    description: 'Panô é Resortwear Carioca — fundada em 2016, a marca captura a leveza e o colorido do Rio de Janeiro em kimonos, pareôs, saídas de praia e vestidos fluidos. Peças que viajam do Leblon para qualquer praia do mundo com a mesma graça.',
    logo: '/logo-pano.png',
  },
  {
    id: '5',
    name: 'Sol Brand',
    state: 'MG',
    category: 'Beachwear',
    slug: 'sol-brand',
    description: 'De Belo Horizonte, Sol Brand cria vestidos, biquínis e moda praia com identidade própria e sofisticação. Com mais de 220 produtos em coleção, a marca combina cortes modernos e tecidos de qualidade para a mulher que brilha onde vai.',
  },
  {
    id: '6',
    name: 'New Match',
    state: 'SP',
    category: 'Roupas',
    slug: 'new-match',
    description: 'New Match é uma marca paulistana contemporânea que une estilo urbano e sofisticação. Com coleções que transitam do dia a dia ao ocasional, cada peça é pensada para a mulher que quer se sentir poderosa sem abrir mão do conforto.',
  },
]

export const products: Product[] = [
  // Amalfi
  {
    id: '1',
    name: 'Top Bandeau Fiore',
    brand: 'Amalfi',
    brandSlug: 'amalfi',
    price: 305,
    category: 'Beachwear',
    sizes: ['PP', 'P', 'M', 'G'],
    slug: 'top-bandeau-fiore',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Top bandeau em tecido de altíssima qualidade com estampa floral exclusiva. Alças removíveis e bojo removível. Ideal para praias e piscinas de resort.',
  },
  {
    id: '2',
    name: 'Conjunto Atoalhado Amalfi',
    brand: 'Amalfi',
    brandSlug: 'amalfi',
    price: 578,
    category: 'Beachwear',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'conjunto-atoalhado-amalfi',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Conjunto em tecido atoalhado premium cor marinho. Cropped manga longa com shorts de cintura alta. Perfeito para o after-beach com muito estilo.',
  },
  {
    id: '3',
    name: 'Saída de Praia Vestido Longo',
    brand: 'Amalfi',
    brandSlug: 'amalfi',
    price: 420,
    category: 'Beachwear',
    sizes: ['P', 'M', 'G'],
    slug: 'saida-praia-vestido-longo',
    image: undefined,
    isNew: false,
    inStock: true,
    description: 'Saída de praia em viscose premium com estampa exclusiva Amalfi. Modelagem fluida e comprimento longo que valoriza qualquer silhueta.',
  },

  // Ares
  {
    id: '4',
    name: 'Blusa Zurique',
    brand: 'Ares',
    brandSlug: 'ares',
    price: 139,
    category: 'Blusas',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'blusa-zurique',
    image: undefined,
    isNew: false,
    inStock: true,
    description: 'Blusa Zurique em tecido fluido com modelagem ampla e manga longa. Perfeita para compor looks casuais e de trabalho. Disponível em várias cores.',
    onSale: true,
  },
  {
    id: '5',
    name: 'Calça Sicília',
    brand: 'Ares',
    brandSlug: 'ares',
    price: 289,
    category: 'Calças',
    sizes: ['34', '36', '38', '40', '42', '44'],
    slug: 'calca-sicilia',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Calça Sicília de corte reto com cintura alta e caimento impecável. Tecido de qualidade que não amassa. Ideal para o dia a dia com conforto e estilo.',
  },
  {
    id: '6',
    name: 'Blusa Nashville',
    brand: 'Ares',
    brandSlug: 'ares',
    price: 129,
    category: 'Blusas',
    sizes: ['PP', 'P', 'M', 'G'],
    slug: 'blusa-nashville',
    image: undefined,
    isNew: false,
    inStock: true,
    description: 'Blusa Nashville com detalhes diferenciados e tecido leve. Modelagem levemente ampla que fica bem em todos os tipos de corpo. Frete grátis acima de R$ 350.',
  },

  // Dress To
  {
    id: '7',
    name: 'Vestido Midi Dress To',
    brand: 'Dress To',
    brandSlug: 'dress-to',
    price: 229,
    category: 'Vestidos',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'vestido-midi-dress-to',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Vestido midi com design moderno e tecido de qualidade. Corte que valoriza a silhueta com elegância descomplicada. Um must-have da coleção Dress To.',
  },
  {
    id: '8',
    name: 'Macacão Dress To',
    brand: 'Dress To',
    brandSlug: 'dress-to',
    price: 259,
    category: 'Macacões',
    sizes: ['PP', 'P', 'M', 'G'],
    slug: 'macacao-dress-to',
    image: undefined,
    isNew: false,
    inStock: true,
    description: 'Macacão pantacourt com decote transpassado e cinto incluso. Tecido fluido com ótimo caimento. Da praia para o jantar com apenas um acessório.',
  },
  {
    id: '9',
    name: 'Blusa Cropped Dress To',
    brand: 'Dress To',
    brandSlug: 'dress-to',
    price: 89,
    category: 'Blusas',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'blusa-cropped-dress-to',
    image: undefined,
    isNew: false,
    inStock: true,
    description: 'Blusa cropped básica com acabamento refinado. Versátil e confortável para o dia a dia. Disponível em cores neutras e vibrantes.',
    onSale: true,
  },

  // Panô
  {
    id: '10',
    name: 'Kimono Carioca Panô',
    brand: 'Panô',
    brandSlug: 'pano',
    price: 319,
    category: 'Resortwear',
    sizes: ['P', 'M', 'G'],
    slug: 'kimono-carioca-pano',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Kimono em voil estampado com estampa exclusiva Panô. Leve, fluido e cheio de personalidade carioca. Use como saída de praia ou peça principal do look.',
  },
  {
    id: '11',
    name: 'Blusa Aquarela',
    brand: 'Panô',
    brandSlug: 'pano',
    price: 209,
    category: 'Blusas',
    sizes: ['PP', 'P', 'M', 'G'],
    slug: 'blusa-aquarela-pano',
    image: undefined,
    isNew: false,
    inStock: true,
    description: 'Blusa em seda lavada com estampa aquarela exclusiva. Toque suave e caimento elegante. Perfeita para dias quentes com saia ou short.',
  },
  {
    id: '12',
    name: 'Vestido Pareô Ipanema',
    brand: 'Panô',
    brandSlug: 'pano',
    price: 349,
    category: 'Vestidos',
    sizes: ['P', 'M', 'G'],
    slug: 'vestido-pareo-ipanema',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Vestido em estilo pareô com amarração lateral e estampa vibrante. Inspira as cores e a energia de Ipanema. Frete grátis acima de R$ 500 para o Sudeste.',
  },

  // Sol Brand
  {
    id: '13',
    name: 'Vestido Midi Sol',
    brand: 'Sol Brand',
    brandSlug: 'sol-brand',
    price: 398,
    category: 'Vestidos',
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    slug: 'vestido-midi-sol',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Vestido midi Sol Brand com corte moderno e tecido premium. Design exclusivo que combina sofisticação e conforto. Uma das peças mais queridinhas da coleção.',
  },
  {
    id: '14',
    name: 'Vestido Longo Festa',
    brand: 'Sol Brand',
    brandSlug: 'sol-brand',
    price: 698,
    category: 'Vestidos',
    sizes: ['PP', 'P', 'M', 'G'],
    slug: 'vestido-longo-festa-sol',
    image: undefined,
    isNew: false,
    inStock: true,
    description: 'Vestido longo para ocasiões especiais. Tecido fluido com acabamento impecável e corte que valoriza a silhueta feminina. De Belo Horizonte para o mundo.',
  },
  {
    id: '15',
    name: 'Biquíni Sol Premium',
    brand: 'Sol Brand',
    brandSlug: 'sol-brand',
    price: 278,
    category: 'Beachwear',
    sizes: ['PP', 'P', 'M', 'G'],
    slug: 'biquini-sol-premium',
    image: undefined,
    isNew: true,
    inStock: true,
    description: 'Biquíni premium Sol Brand com corte moderno e tecido de alta resistência UV. Design exclusivo inspirado no sol de Minas para as praias do Brasil.',
  },
]

export const categories = ['Novidades', 'Roupas', 'Vestidos', 'Blusas', 'Beachwear', 'Acessórios', 'Sale']

export function getProductsByBrand(brandSlug: string): Product[] {
  return products.filter((p) => p.brandSlug === brandSlug)
}

export function getBrandBySlug(slug: string): Brand | undefined {
  return brands.find((b) => b.slug === slug)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}
